import './VideoContainer.scss';

const VideoContainer = () => {
  return (
    <div className="video-container">
        <p>video container</p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores at earum animi quia facere reprehenderit voluptatum magnam nulla aspernatur perferendis excepturi, dicta nisi natus in. Doloribus voluptates distinctio labore delectus.

    </div>
  )
}

export default VideoContainer;